export const ASYNC_WELFARE_SUCCESS = 'ASYNC_WELFARE_SUCCESS';
export const ASYNC_WELFARE_ERROR = 'ASYNC_WELFARE_ERROR';
export const ASYNC_WELFARE_REQUEST = 'ASYNC_WELFARE_REQUEST';

export const ASYNC_LOCAL_SUCCESS = 'ASYNC_LOCAL_SUCCESS';
export const ASYNC_LOCAL_ERROR = 'ASYNC_LOCAL_ERROR';
export const ASYNC_LOCAL_REQUEST = 'ASYNC_LOCAL_REQUEST';
export const ASYNC_LOCAL_REQUEST_UPDATE = 'ASYNC_LOCAL_REQUEST_UPDATE';
export const ASYNC_LOCAL_SUCCESS_UPDATE = 'ASYNC_LOCAL_SUCCESS_UPDATE';